// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_91fpz3smg0f0T7k-tGyH8lLlzoNBUjQ',
    appId: '1:499711424182:web:612f9738c1625f8206d817',
    messagingSenderId: '499711424182',
    projectId: 'arecanut-app-flutter',
    authDomain: 'arecanut-app-flutter.firebaseapp.com',
    storageBucket: 'arecanut-app-flutter.appspot.com',
    measurementId: 'G-4VC4K610RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe__C1J5cWVRuRviWdMwinDg2h77wTWho',
    appId: '1:499711424182:android:630771a96ff947e206d817',
    messagingSenderId: '499711424182',
    projectId: 'arecanut-app-flutter',
    storageBucket: 'arecanut-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEe_kQXTn3tq-t-gO6mejMLyNgbJuoMOU',
    appId: '1:499711424182:ios:5349aab430141fa006d817',
    messagingSenderId: '499711424182',
    projectId: 'arecanut-app-flutter',
    storageBucket: 'arecanut-app-flutter.appspot.com',
    iosClientId: '499711424182-r54carla4voj4ftbdddcr3q4obqtdn3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.arecanutApp',
  );
}
